In [1]:
import csv

with open(file="try.csv" , mode='r') as f:
    reader = csv.reader(f)
    
    for row in reader:
        print(row)

['Name', 'Address', 'Age']
['Ram', 'Biratnagar', '22']
['Shyam', 'Itahari', '24']
['Hari', 'Dharan', '23']

In [3]:
import csv

with open("try.csv", "r") as f:
    reader = csv.DictReader(f)
    for row in reader:
        print(row)

{'Name': 'Ram', 'Address': 'Biratnagar', 'Age': '22'}
{'Name': 'Shyam', 'Address': 'Itahari', 'Age': '24'}
{'Name': 'Hari', 'Address': 'Dharan', 'Age': '23'}

In [6]:
import csv

with open(file="try.csv" , mode='r') as f:
    reader = csv.DictReader(f)
    
    for row in reader:
        print(row)
        print(row['Name'] , row['Address'] , row['Age'])

{'Name': 'Ram', 'Address': 'Biratnagar', 'Age': '22'}
Ram Biratnagar 22
{'Name': 'Shyam', 'Address': 'Itahari', 'Age': '24'}
Shyam Itahari 24
{'Name': 'Hari', 'Address': 'Dharan', 'Age': '23'}
Hari Dharan 23

In [ ]:
import csv

data = [
    ["Name", "Address", "Age"],
    ["Ram", "Biratnagar", "22"],
    ["Shyam", "Itahari", "24"],
    ["Hari", "Dharan", "23"],
]

additional_data = ['Himal', "Dharan" , "23"]
with open(file="newnew.csv" , mode='w' , newline="") as f:
    writer = csv.writer(f)
    writer.writerows(data)
    
    writer.writerow(additional_data)

In [14]:
data = [
    {"name": "Himal", "age": 30},
    {"name": "Sajina", "age": 10},
    {"name": "Heemal", "age": 33},
]
with open(file="output.csv", mode="w") as f:
    writer = csv.DictWriter(f, fieldnames=["name", "age"])
    writer.writeheader()
    writer.writerows(data)

In [ ]:
import pandas as pd

df = pd.read_csv('newnew.csv')    # DataFrame vanne class ko object ho.
print(df)
print(type(df))

# df["Address"] # to access individual columns
# df['Age']

    Name     Address  Age
0    Ram  Biratnagar   22
1  Shyam     Itahari   24
2   Hari      Dharan   23
3  Himal      Dharan   23
<class 'pandas.core.frame.DataFrame'>

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     4 non-null      object
 1   Address  4 non-null      object
 2   Age      4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [ ]:
df.head(2)  # to retrieve the information

    Name     Address  Age
0    Ram  Biratnagar   22
1  Shyam     Itahari   24

In [31]:
df.tail(2)

    Name Address  Age
2   Hari  Dharan   23
3  Himal  Dharan   23

In [ ]:
# to view the random sample


df.sample()  # gives the different sample from the existing csv file.

    Name Address  Age
3  Himal  Dharan   23

In [ ]:
# to check the missing values.

# df.isnull()

df.isnull().sum()  # to find out the missing values

Name       0
Address    0
Age        0
dtype: int64

In [49]:
# To add the columns


df["Province"] = "Koshi"

In [50]:
print(df)

    Name     Address  Age Province
0    Ram  Biratnagar   22    Koshi
1  Shyam     Itahari   24    Koshi
2   Hari      Dharan   23    Koshi
3  Himal      Dharan   23    Koshi

In [51]:
# to write the csv back

df.to_csv("newwrite.csv" , index=False) # index csv file ma chaideina so we use false

In [ ]:
data = [
    {"Roll": 1, "Name": "Ram", "English": 80, "Math": 81, "Science": 82},
    {"Roll": 2, "Name": "Shyam", "English": 79, "Math": 80, "Science": 83},
]
dataframe = pd.DataFrame(data=data)  # total vanne chaiyo. and then percentage vanne banaune.

dataframe["Total"] = dataframe["English"] + dataframe["Math"] + dataframe["Science"]
print(dataframe)

   Roll   Name  English  Math  Science  Total
0     1    Ram       80    81       82    243
1     2  Shyam       79    80       83    242

In [70]:
dataframe['Percentage'] =(dataframe['Total']/3).round(decimals=2)
print(dataframe)

   Roll   Name  English  Math  Science  Total  Percentage
0     1    Ram       80    81       82    243       81.00
1     2  Shyam       79    80       83    242       80.67

In [71]:
dataframe.to_csv("newFile.csv", index=False)

In [82]:
# Reading a Json File

import json
import pprint

with open(file="data.json" ,mode='r') as f:
    json_parsed = json.load(f)
    # print(json_parsed)
    pprint.pprint(json_parsed)

{'Additional': {'Age': 34, 'Name': 'Himal'},
 'Address': 'Dharan',
 'Age': 34,
 'Name': 'Himal'}

In [83]:
import json 

data = {
    "Name":"Himal Bhandari",
    "Age":20,
    "Address":"Jhapa"    
}

with open(file="newJson.json", mode='w') as f:
    json.dump(data , f , indent=4)

In [8]:
import plotly.express as px
import pandas as pd

df = px.data.iris()

print(df.head())

fig = px.scatter(df, x= "sepal_length", y= "sepal_width")

fig.show()

fig1 = px.bar(df, x= "sepal_length", y= "species")

fig1.show()

fig1.write_html("plot.html")

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1